Gemfile
Gemfile.lock
app/assets/javascripts/application.js
app/assets/stylesheets/application.scss
app/views/layouts/application.html.erb

[Add]header,footer

---

config/routes.rb

Feature routes

---

app/views/layouts/_header_customer.html.erb
app/views/layouts/application.html.erb

Feature customer header

---

app/controllers/admins/sessions_controller.rb
app/views/layouts/_header_admin.html.erb
db/seeds.rb

https://qiita.com/shinji0320/items/addc05acbe38c65b9190
↑の手順で
管理者をseeds.rbに記述し、登録しました。

Add admin sessions(seeds.rb)

---

app/assets/stylesheets/application.scss
app/controllers/application_controller.rb
app/views/customers/registrations/new.html.erb
app/views/customers/sessions/new.html.erb

#ログイン、サインアップページ(customer側)の作成
ー　application_controllerにストロングパラメーター追加しました
　　以下のURL参考にして、ログイン後のリダイレクト先も記述しました(admin側のリダイレクト先も)
https://qiita.com/IsakiMatsuo/items/4f72c65584c2c9892961
ー　application.scssにも記述しました

[devise]customer-sign_in_up

---

app/assets/javascripts/customers/homes.coffee
app/assets/stylesheets/customers/homes.scss
app/controllers/customers/homes_controller.rb
app/helpers/customers/homes_helper.rb
app/views/customers/homes/about.html.erb
app/views/customers/homes/top.html.erb
config/routes.rb
test/controllers/customers/homes_controller_test.rb

customersのTopページ、Aboutページを追加しました。

[Add] customer top,about

---

app/assets/javascripts/customers/customers.coffee
app/assets/stylesheets/customers/customers.scss
app/controllers/customers/customers_controller.rb
app/helpers/customers/customers_helper.rb
app/models/customer.rb
app/views/customers/customers/edit.html.erb
app/views/customers/customers/show.html.erb
app/views/customers/customers/unsubscribe.html.erb
app/views/customers/homes/about.html.erb
app/views/customers/homes/top.html.erb
app/views/customers/registrations/edit.html.erb
app/views/customers/sessions/new.html.erb
app/views/layouts/_header_customer.html.erb
config/routes.rb
test/controllers/customers/customers_controller_test.rb

#customerのshow,edit,unsubscribeページ作成しました。(マイページ、編集ページ、退会ページ)
ー　退会アクションも記述しました(customerモデルにも記述しました。)
ー　退会後topページに遷移して、フラッシュメッセージ出るようにしました(わかりやすいように一応)
ー　routesで、devise_for :customerの位置をmodule: :customersの下に下げました
　　(customerのeditページよりもregistraitonのeditページが先に反応してしまった為)

Feature customer pages

---

app/assets/javascripts/admins/genres.coffee
app/assets/stylesheets/admins/genres.scss
app/controllers/admins/genres_controller.rb
app/helpers/admins/genres_helper.rb
app/views/admins/genres/edit.html.erb
app/views/admins/genres/index.html.erb
test/controllers/admins/genres_controller_test.rb

管理者側のジャンルのviewページ２種をかなり適当に作りました。

admin-genres(view)

---

app/assets/javascripts/admins/homes.coffee
app/assets/stylesheets/admins/homes.scss
app/controllers/admins/homes_controller.rb
app/controllers/admins/sessions_controller.rb
app/helpers/admins/homes_helper.rb
app/views/layouts/_header_admin.html.erb
test/controllers/admins/homes_controller_test.rb

[Update] adminのloginページ

---

app/controllers/admins/products_controller.rb
app/controllers/customers/orders_controller.rb
app/models/order.rb
app/views/customers/orders/confirm.html.erb
app/views/customers/orders/new.html.erb

Customerのorder関連ページ作成しました
- createコントローラー、カート情報などはまだ記入してませんが、エラーないので一旦pushしときます

customer_order_pages

---

app/assets/stylesheets/customers/homes.css
app/assets/stylesheets/customers/homes.scss
app/controllers/customers/cart_products_controller.rb
app/models/product.rb
app/views/customers/cart_products/index.html.erb
app/views/customers/homes/top.html.erb
app/views/customers/products/index.html.erb
app/views/customers/products/show.html.erb
app/views/layouts/_header_customer.html.erb
config/routes.rb

ショッピングカートの機能を実装完了しました。デザインは少し訂正が必要ですがほぼ完成しました。

Feature customer products

---

app/controllers/customers/orders_controller.rb
app/models/order.rb
app/views/customers/orders/confirm.html.erb
app/views/customers/orders/new.html.erb
config/routes.rb

注文のconfirmページにて、情報の表示はできました。
- 今は注文確定ボタンでthanksページに遷移するようには設定してます。
- createの記述が何もないので、orderの情報を登録するための記述が空になってます。

confirm_page

---

app/assets/stylesheets/admins/genres.scss
app/views/admins/genres/edit.html.erb
app/views/admins/genres/index.html.erb
app/views/admins/products/edit.html.erb

#ジャンル一覧ページおよびジャンル編集ページのレイアウトを作成しました

Update admin products layout

---

app/assets/stylesheets/admins/customers.scss
app/assets/stylesheets/application.scss
app/controllers/admins/customers_controller.rb
app/views/admins/customers/index.html.erb
app/views/kaminari/_first_page.html.erb
app/views/kaminari/_gap.html.erb
app/views/kaminari/_last_page.html.erb
app/views/kaminari/_next_page.html.erb
app/views/kaminari/_page.html.erb
app/views/kaminari/_paginator.html.erb
app/views/kaminari/_prev_page.html.erb
config/initializers/kaminari_config.rb
config/locales/ja.yml

管理者側の会員情報のindexページのレイアウトを修正しました。

Feature admin customers

---

app/controllers/customers/orders_controller.rb
app/models/cart_product.rb
app/models/order.rb
app/models/order_product.rb
app/models/product.rb
app/views/customers/orders/confirm.html.erb
app/views/customers/orders/index.html.erb
app/views/customers/orders/sub.html.erb

#order関係のページ全て作成完了しました。
- 動作確認済みで、エラーなど出ませんでした。

[finish] order_pages

---

app/assets/javascripts/customers/searches.coffee
app/assets/stylesheets/application.scss
app/assets/stylesheets/customers/searches.scss
app/controllers/customers/searches_controller.rb
app/helpers/customers/searches_helper.rb
app/models/product.rb
app/views/customers/homes/top.html.erb
app/views/customers/orders/show.html.erb
app/views/customers/searches/search.html.erb
app/views/layouts/_header_customer.html.erb
app/views/layouts/application.html.erb
config/routes.rb
test/controllers/customers/searches_controller_test.rb

ヘッダーに検索機能を追加しました。
カートの商品全て削除のバグを直しました。

[Add]Search　fix bug

---

app/assets/stylesheets/admins/homes.scss
app/assets/stylesheets/admins/orders.scss
app/views/admins/homes/top.html.erb
app/views/admins/orders/show.html.erb

管理者側の注文履歴のindex,showページのレイアウトを調整しました。

feature-admin-orders

---

app/controllers/admins/homes_controller.rb
app/views/admins/homes/top.html.erb

管理者側の注文履歴のindexページにページネーションを追加しました。

[Update] adminのorderのindexページ

---

app/assets/javascripts/admins/searches.coffee
app/assets/stylesheets/admins/searches.scss
app/controllers/admins/searches_controller.rb
app/helpers/admins/searches_helper.rb
app/views/admins/searches/search.html.erb
app/views/layouts/_header_admin.html.erb
config/routes.rb
test/controllers/admins/searches_controller_test.rb

[Update] adminのheader

---

app/assets/stylesheets/admins/customers.scss
app/assets/stylesheets/admins/homes.scss
app/controllers/admins/homes_controller.rb
app/controllers/admins/order_products_controller.rb
app/controllers/admins/orders_controller.rb
app/views/admins/homes/top.html.erb
app/views/layouts/application.html.erb

管理者側の注文履歴のshowページの注文ステータスと製作ステータスを
それぞれ連動して自動更新するように変更しました。
また、注文履歴のindexページを最新順に表示するように変更しました。
レイアウトは、後ほど修正します。

Feature admin status

---

app/assets/stylesheets/admins/genres.scss
app/assets/stylesheets/admins/homes.scss
app/views/admins/genres/edit.html.erb
app/views/admins/products/index.html.erb
app/views/admins/sessions/new.html.erb

Feature layout

---

app/views/admins/orders/show.html.erb

管理者側の注文履歴の詳細ページの
会員詳細ページへのリンクのエラーを修正しました。

[Update] adminのorderのshowページ
